#!/usr/bin/env python3
"""
run_analysis.py — Group-level analysis pipeline (concat → smooth → GLM).

Assumes per-patient preprocessing is complete:
  • Coregistration (mri_coreg) → template.reg.lta
  • Partial volume correction (mri_gtmpvc) → gtmpvc output folder
  • Surface projection (mri_vol2surf) → {lh,rh}.pet.fsaverage.sm00.nii.gz

This script picks up from those outputs and runs:
  1. mri_concat  — concatenate all subjects per hemisphere
  2. mris_fwhm   — smooth the concatenated surface map
  3. mri_glmfit  — GLM on the smoothed map (requires FSGD + contrast matrix)

The FSGD file can be provided via --fsgd-path; if omitted, it is auto-generated
from the input Excel file using the same column conventions as excel_to_fsgd.py.

Usage:
    python src/run_analysis.py braak-stage/

The analysis directory must contain:
  • Exactly one *.xlsx  → patient list
  • One or more *.mtx   → contrast matrices
  • At most one *.fsgd  → existing FSGD (if absent, one is auto-generated)

All outputs (concat, smooth, GLM, FSGD, log) are written into that directory.
Explicit flags override auto-discovery:

    python src/run_analysis.py braak-stage/ \\
        [--excel-path patients.xlsx] \\
        [--contrast-matrix-path c1.mtx c2.mtx] \\
        [--subjects-dir ./data] \\
        [--fwhm 10] \\
        [--fsgd-path existing.fsgd] \\
        [--title "MyStudy"] \\
        [--default-var Age] \\
        [--mean-center] \\
        [--design dods|doss] \\
        [--subjects-template YASMINE_TAU_%d_%s]
"""

import argparse
import logging
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

# Allow imports from src/
sys.path.insert(0, os.path.dirname(__file__))

from utils.excel_to_fsgd import (
    build_class_label,
    classify_columns,
    generate_fsgd,
    read_excel,
    validate,
)
from utils.utils import read_patients_from_excel

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

HEMISPHERES = ('lh', 'rh')

# Vol2surf output expected inside each subject's mri/ directory
VOL2SURF_FILENAME = '{hemi}.pet.fsaverage.sm00.nii.gz'

# First line written to auto-generated FSGD files so re-runs can detect and regenerate them
FSGD_GENERATED_MARKER = '# Generated by run_analysis.py'


# ---------------------------------------------------------------------------
# Input auto-discovery
# ---------------------------------------------------------------------------

def resolve_inputs(args: argparse.Namespace, logger: logging.Logger) -> None:
    """
    Auto-discover inputs from args.analysis_dir when explicit flags are absent.
    Fills in args.excel_path, args.contrast_matrix_path, and args.fsgd_path in-place.
    Exits with a clear error if required files are missing or ambiguous.
    """
    d = args.analysis_dir

    if not os.path.isdir(d):
        logger.error('Analysis directory not found: %s', d)
        sys.exit(1)

    # --- Excel ---
    if not args.excel_path:
        spreadsheets = sorted(
            Path(d).glob('*.xlsx')
        ) + sorted(
            Path(d).glob('*.xls')
        ) + sorted(
            Path(d).glob('*.ods')
        )
        if len(spreadsheets) == 0:
            logger.error(
                'No spreadsheet (.xlsx or .ods) found in %s. Add your patient list '
                'spreadsheet or pass --excel-path explicitly.', d
            )
            sys.exit(1)
        if len(spreadsheets) > 1:
            logger.error(
                'Multiple spreadsheets found in %s:\n  %s\n'
                'Keep only one, or pass --excel-path to specify which one to use.',
                d, '\n  '.join(str(f) for f in spreadsheets)
            )
            sys.exit(1)
        args.excel_path = str(spreadsheets[0])
        logger.info('[DISCOVERY] Excel: %s', args.excel_path)

    # --- Contrast matrices ---
    if not args.contrast_matrix_path:
        mtx_files = sorted(Path(d).glob('*.mtx'))
        if len(mtx_files) == 0:
            logger.error(
                'No .mtx contrast matrix file(s) found in %s. Add at least one '
                'or pass --contrast-matrix-path explicitly.', d
            )
            sys.exit(1)
        args.contrast_matrix_path = [str(f) for f in mtx_files]
        logger.info('[DISCOVERY] Contrast matrices: %s', ', '.join(args.contrast_matrix_path))

    # --- FSGD (optional) ---
    if not args.fsgd_path:
        fsgd_files = sorted(Path(d).glob('*.fsgd'))
        if len(fsgd_files) > 1:
            logger.error(
                'Multiple .fsgd files found in %s:\n  %s\n'
                'Use --fsgd-path to specify which one to use.',
                d, '\n  '.join(str(f) for f in fsgd_files)
            )
            sys.exit(1)
        if len(fsgd_files) == 1:
            fsgd_file = fsgd_files[0]
            last_line = fsgd_file.read_text().rstrip('\n').rsplit('\n', 1)[-1]
            if last_line.strip() == FSGD_GENERATED_MARKER:
                logger.info('[DISCOVERY] FSGD: %s (auto-generated, will be regenerated)', fsgd_file)
            else:
                args.fsgd_path = str(fsgd_file)
                logger.info('[DISCOVERY] FSGD: %s (user-provided, will be used as-is)', fsgd_file)


# ---------------------------------------------------------------------------
# Preprocessing validation
# ---------------------------------------------------------------------------

def check_vol2surf_outputs(
    patients: list[tuple[int, str]],
    subjects_dir: str,
    subjects_template: str,
    logger: logging.Logger,
) -> bool:
    """
    Verify that mri_vol2surf outputs exist for every patient and hemisphere.
    Logs all missing files at once and returns False if any are absent.
    Call this before running concat so failures are caught early.
    """
    missing: list[str] = []

    for patient_id, timestamp in patients:
        subject_name = subjects_template % (patient_id, timestamp)
        mri_dir = os.path.join(subjects_dir, subject_name, 'mri')
        for hemi in HEMISPHERES:
            path = os.path.join(mri_dir, VOL2SURF_FILENAME.format(hemi=hemi))
            if not os.path.exists(path):
                missing.append(path)

    if missing:
        logger.error(
            'Missing vol2surf output(s) — %d file(s) not found:\n  %s\n\n'
            'These files are produced by the preprocessing step (mri_vol2surf).\n'
            'Run the preprocessing pipeline first to generate these outputs before '
            'running run_analysis.py.',
            len(missing),
            '\n  '.join(missing),
        )
        return False

    return True


# ---------------------------------------------------------------------------
# FSGD generation
# ---------------------------------------------------------------------------

def resolve_fsgd(args: argparse.Namespace, output_dir: str, logger: logging.Logger) -> str:
    """
    Return the path to the FSGD file to use for GLM.
    If --fsgd-path is given, validate it exists and return it.
    Otherwise, auto-generate from the Excel file and write to output_dir/analysis.fsgd.
    """
    if args.fsgd_path:
        if not os.path.exists(args.fsgd_path):
            logger.error('FSGD file not found: %s', args.fsgd_path)
            sys.exit(1)
        logger.info('[FSGD] Using provided file: %s', args.fsgd_path)
        return args.fsgd_path

    # Auto-generate — title defaults to the analysis directory name
    title = args.title or Path(output_dir).resolve().name
    logger.info('[FSGD] Auto-generating from Excel: %s (title: %s)', args.excel_path, title)

    headers, data_rows = read_excel(args.excel_path)
    discrete_cols, continuous_cols = classify_columns(headers, data_rows)

    if not validate(
        headers, data_rows, discrete_cols, continuous_cols,
        args.default_var, args.subjects_template,
    ):
        logger.error('FSGD validation failed. Fix the errors above and retry.')
        sys.exit(1)

    fsgd_content = generate_fsgd(
        headers=headers,
        data_rows=data_rows,
        discrete_cols=discrete_cols,
        continuous_cols=continuous_cols,
        title=title,
        default_var=args.default_var,
        mean_center=args.mean_center,
        subjects_template=args.subjects_template,
    )

    fsgd_path = os.path.join(output_dir, 'analysis.fsgd')
    Path(fsgd_path).write_text(fsgd_content + FSGD_GENERATED_MARKER + '\n')
    logger.info('[FSGD] Written to: %s', fsgd_path)
    return fsgd_path


# ---------------------------------------------------------------------------
# Main analysis steps
# ---------------------------------------------------------------------------

def run_analysis(args: argparse.Namespace, logger: logging.Logger) -> None:
    subjects_dir = args.subjects_dir
    output_dir = args.analysis_dir
    fwhm = args.fwhm
    subjects_template = args.subjects_template

    os.makedirs(output_dir, exist_ok=True)

    # --- Auto-discover inputs from analysis directory ---
    resolve_inputs(args, logger)

    # --- Read patient list ---
    patients = read_patients_from_excel(args.excel_path)
    if not patients:
        logger.error('No patients found in %s. Check the include flag (column 1).', args.excel_path)
        sys.exit(1)
    logger.info('Loaded %d patient scan(s) from %s', len(patients), args.excel_path)

    # --- Validate directories ---
    if not os.path.isdir(subjects_dir):
        logger.error(
            'Subjects directory not found: %s\n'
            'Pass --subjects-dir with the correct path.', subjects_dir
        )
        sys.exit(1)

    # --- Validate preprocessing outputs (fail fast, list everything at once) ---
    if not check_vol2surf_outputs(patients, subjects_dir, subjects_template, logger):
        sys.exit(1)

    # --- Collect per-hemisphere vol2surf paths ---
    vol2surf_paths: dict[str, list[str]] = {hemi: [] for hemi in HEMISPHERES}
    for patient_id, timestamp in patients:
        subject_name = subjects_template % (patient_id, timestamp)
        mri_dir = os.path.join(subjects_dir, subject_name, 'mri')
        for hemi in HEMISPHERES:
            vol2surf_paths[hemi].append(
                os.path.join(mri_dir, VOL2SURF_FILENAME.format(hemi=hemi))
            )

    # --- FSGD ---
    fsgd_path = resolve_fsgd(args, output_dir, logger)

    # --- Per-hemisphere: concat → smooth → GLM ---
    for hemi in HEMISPHERES:
        # Concat
        concat_path = os.path.join(output_dir, f'all.{hemi}.pet.fsaverage.sm00.nii.gz')
        logger.info('[RUNNING] concat %s — %d subjects', hemi, len(patients))
        result = subprocess.run(
            ['mri_concat'] + vol2surf_paths[hemi] + ['--o', concat_path, '--prune'],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
        )
        logger.debug('[OUTPUT] mri_concat %s stdout:\n%s\nstderr:\n%s', hemi, result.stdout, result.stderr)
        if result.returncode != 0:
            logger.error(
                'mri_concat failed for %s (exit code %d). See the log file for details.',
                hemi, result.returncode,
            )
            sys.exit(1)
        logger.info('[DONE] concat %s → %s', hemi, concat_path)

        # Smooth
        smoothed_path = os.path.join(
            output_dir, f'all.{hemi}.pet.fsaverage.sm{fwhm:02d}.nii.gz'
        )
        logger.info('[RUNNING] smooth %s (fwhm=%d)', hemi, fwhm)
        result = subprocess.run([
            'mris_fwhm',
            '--smooth-only',
            '--i',     concat_path,
            '--fwhm',  str(fwhm),
            '--o',     smoothed_path,
            '--cortex',
            '--s',     'fsaverage',
            '--hemi',  hemi,
        ], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        logger.debug('[OUTPUT] mris_fwhm %s stdout:\n%s\nstderr:\n%s', hemi, result.stdout, result.stderr)
        if result.returncode != 0:
            logger.error(
                'mris_fwhm failed for %s (exit code %d). See the log file for details.',
                hemi, result.returncode,
            )
            sys.exit(1)
        logger.info('[DONE] smooth %s → %s', hemi, smoothed_path)

        # GLM
        glmfit_dir = os.path.join(
            output_dir, f'all.{hemi}.pet.fsaverage.sm{fwhm:02d}.glmfit'
        )
        logger.info('[RUNNING] glmfit %s', hemi)
        contrast_flags = []
        for c in args.contrast_matrix_path:
            contrast_flags += ['--C', c]
        result = subprocess.run([
            'mri_glmfit',
            '--y',      smoothed_path,
            '--fsgd',   fsgd_path, args.design,
            *contrast_flags,
            '--surf',   'fsaverage', hemi,
            '--cortex',
            '--o',      glmfit_dir,
        ], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        logger.debug('[OUTPUT] mri_glmfit %s stdout:\n%s\nstderr:\n%s', hemi, result.stdout, result.stderr)
        if result.returncode != 0:
            logger.error(
                'mri_glmfit failed for %s (exit code %d). See the log file for details.',
                hemi, result.returncode,
            )
            sys.exit(1)
        logger.info('[DONE] glmfit %s → %s', hemi, glmfit_dir)

    logger.info('Analysis complete. All outputs written to: %s', output_dir)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            'Run group-level PET surface analysis: concat → smooth → GLM.\n\n'
            'Assumes per-patient preprocessing is complete (coregistration, '
            'gtmpvc, vol2surf). See README.md § Pipeline Steps for the full '
            'preprocessing workflow.'
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    # --- Analysis directory ---
    parser.add_argument(
        'analysis_dir',
        help=(
            'Directory containing analysis inputs: one *.xlsx, one or more *.mtx, '
            'and optionally one *.fsgd. All outputs are written here. '
            'Explicit flags below override anything found in this directory.'
        ),
    )

    # --- Inputs (optional: auto-discovered from analysis_dir) ---
    parser.add_argument(
        '--excel-path', default=None,
        help='Path to the patient list Excel file (.xlsx). Auto-discovered from analysis_dir if omitted.',
    )
    parser.add_argument(
        '--contrast-matrix-path', nargs='+', default=None,
        help='Path(s) to GLM contrast matrix file(s) (.mtx). Auto-discovered from analysis_dir if omitted.',
    )

    # --- Subjects directory ---
    parser.add_argument(
        '--subjects-dir', default='/media/vmalotaux/data/subjects-v.7.2.0',
        help='Root directory containing FreeSurfer subject folders. Default: /media/vmalotaux/data/subjects-v.7.2.0',
    )

    # --- Analysis parameters ---
    parser.add_argument(
        '--fwhm', type=int, default=5,
        help='Surface smoothing kernel FWHM in mm. Default: 5',
    )
    parser.add_argument(
        '--subjects-template', default='YASMINE_TAU_%d_%s',
        help=(
            'printf-style template for subject directory names. '
            'Must contain %%d (patient ID) then %%s (timestamp). '
            'Default: YASMINE_TAU_%%d_%%s'
        ),
    )

    # --- FSGD ---
    fsgd_group = parser.add_argument_group(
        'FSGD',
        'Provide --fsgd-path to use an existing FSGD file, or omit it to '
        'auto-generate one from the Excel file.',
    )
    fsgd_group.add_argument(
        '--fsgd-path', default=None,
        help='Path to an existing FSGD file. If given, FSGD generation is skipped.',
    )
    fsgd_group.add_argument(
        '--title', default=None,
        help='Title for the auto-generated FSGD file. Defaults to the analysis directory name.',
    )
    fsgd_group.add_argument(
        '--default-var', default=None,
        help='Default continuous variable for FSGD display.',
    )
    fsgd_group.add_argument(
        '--mean-center', action='store_true',
        help='Mean-center continuous variables in the auto-generated FSGD.',
    )
    fsgd_group.add_argument(
        '--design', default='dods', choices=['dods', 'doss'],
        help=(
            'GLM design type passed to mri_glmfit via --fsgd: '
            'dods = Different Offset Different Slope, '
            'doss = Different Offset Same Slope. Default: dods'
        ),
    )

    return parser.parse_args()


def setup_logger(output_dir: str) -> logging.Logger:
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    log_path = os.path.join(output_dir, f'analysis_{timestamp}.log')

    logger = logging.getLogger('run_analysis')
    logger.setLevel(logging.DEBUG)  # let handlers decide what to show
    logger.propagate = False

    fmt = logging.Formatter('%(asctime)s  %(levelname)-8s  %(message)s', datefmt='%Y-%m-%d %H:%M:%S')

    file_handler = logging.FileHandler(log_path, mode='w')
    file_handler.setFormatter(fmt)
    file_handler.setLevel(logging.DEBUG)
    logger.addHandler(file_handler)

    stream_handler = logging.StreamHandler(sys.stdout)
    stream_handler.setFormatter(fmt)
    stream_handler.setLevel(logging.INFO)
    logger.addHandler(stream_handler)

    logger.info('Log file: %s', log_path)
    return logger, log_path


if __name__ == '__main__':
    args = parse_args()
    logger, log_path = setup_logger(args.analysis_dir)
    try:
        run_analysis(args, logger)
    except ValueError as e:
        logger.debug('Validation error details:\n%s', e)
        logger.error('Input error — see the log file for details: %s', log_path)
        sys.exit(1)
    except Exception as e:
        logger.exception('Unexpected error: %s', e)
        sys.exit(1)
